### POST /api/phonebill/
POST http://localhost:5008/api/phonebill
Content-Type: application/json

{
    "price_plan": "sms 101",
    "actions": "call, sms, call"
}

###

### GET /api/price_plans/
GET http://localhost:5008/api/price_plans
Content-Type: application/json

###

### POST /api/price_plan/create
POST http://localhost:5008/api/price_plan/create
Content-Type: application/json

{
    "name": "sms 101",
    "call_cost": 2.65,
    "sms_cost": 0.45
}

###

### POST /api/price_plan/update
POST http://localhost:5008/api/price_plan/update
Content-Type: application/json

{
    "name": "sms 101",
    "call_cost": 2.75,
    "sms_cost": 0.50
}

###

### POST /api/price_plan/delete
POST http://localhost:5008/api/price_plan/delete
Content-Type: application/json

{
    "id": 9
}